<?php
// $Id$

/**
 * Implementation of hook_install()
 */
function akv_pagepeels_install() {
  variable_set('akv_type', 'latest');
  variable_set('akv_info', 'on');
  variable_set('akv_html','/html/akv_pagepeels.html'); 
  variable_del('akv_css', '/css/akv_pagepeels_latest.css');  
}

/**
 * Implementation of hook_uninstall()
 */
function akv_pagepeels_uninstall() {
  variable_del('akv_type');
  variable_del('akv_info');
  variable_del('akv_html'); 
  variable_del('akv_css');  
}
?>