<?php

/**
 * @file
 * Contains akv_pagepeels.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function akv_pagepeels_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the akv_pagepeels module.
    case 'help.page.akv_pagepeels':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Displays a pagepeel for the german movement against "Vorratsdatenspeicherung", www.vorratsdatenspeicherung.de') . '</p>';
      return $output;

    default:
  }
}
